apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.dev.yml
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: otel3-flask
  name: otel3-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: otel3-flask
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.dev.yml
        kompose.version: 1.22.0 (955b78124)
        sidecar.opentelemetry.io/inject: "true"
      creationTimestamp: null
      labels:
        io.kompose.service: otel3-flask
    spec:
      containers:
        - image: docker.io/haoruibing/otel3-flask
          name: otel3-flask
          env:
           - name: SERVICE_NAME
             value: "otel-agent-tracing-metrics"
           - name: AGENT_HOST
             value: "localhost"
           - name: AGENT_PORT
             value: "6831"
          ports:
           - containerPort: 5000 
      restartPolicy: Always
status: {}